FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ..

RUN apt update \
    && apt install -y gcc default-libmysqlclient-dev pkg-config \
    && apt install weasyprint -y \
    && pip install --no-cache-dir -r requirements.txt \
    && apt remove -y gcc pkg-config \
    && apt autoremove -y \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

COPY . . 

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]